# Generated by Django 6.0.4 on 2026-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='estimation',
            field=models.DurationField(blank=True, help_text='Estimated effort (e.g. 2:30:00 for 2h 30min)', null=True),
        ),
    ]
